# 공통 설정
debug: false # Disable debug log

logging:
  level: # 해당 패키지 이하에서 발생하는 로그는 설정 단계 이상부터만 보겠다.
    hyeong.lee.myboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_board
    username: hyeong
    password: thisisTESTpw!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB # 개별 파일의 최대 사이즈
      max-request-size: 30MB # 한꺼번에 보낼 수 있는 최대 사이즈
  jpa:
    show-sql: true # hibernate가 DB에 날리는 모든 쿼리를 보여주세요
    hibernate.ddl-auto: update # 실행 시 테이블을 모두 drop 이후 새로 create
    defer-datasource-initialization: true # 테스트용 데이터를 미리 설정,이용할 수 있다 (data.sql 내)
    properties: # JPA 구현체(Hibernate)에 종속된 설정
      hibernate.format_sql: true  # SQL을 보기좋게 포매팅 해주세요
      hibernate.default_batch_fetch_size: 100 # 여러 쿼리를 한방에 벌크로 긁어오도록 해주세요 (N+1문제 관련)
  sql.init.mode: never  # 테스트용 데이터는 언제 사용할 것인지? (data.sql)
  mvc:
    static-path-pattern: /resources/** # 정적 리소스에 접근할 때는 항상 아래 경로로 요청
  messages: # 메세지 소스 설정
    basename: errors

# 저장소 경로 변수
resources.location: C:\Users\HOME\Desktop\Java_study\MySimpleBoardService\storage

--- # 로컬 환경 설정
spring:
  config:
    activate:
      on-profile: local

--- # 배포 환경 (Prod)

spring:
  config:
    activate:
      on-profile: prod

resources.location: /home/ec2-user/app/mySimpleBoardService_build/storage # 클라우드 환경 저장소 경로